module.exports = {
	COMMUNITY_CHAT:"COMMUNITY_CHAT",
	USER_CONNECTED:"USER_CONNECTED",
	MESSAGE_SENT:"MESSAGE_SENT",
	USER_DISCONNECTED:"USER_DISCONNECTED",
	LOGOUT:"LOGOUT",
	SEND_OFF_MSG:"SEND_OFF_MSG",
	UNREAD_MSG:"UNREAD_MSG"
}